### ISSUE TITLE
improve consistensy of tasks made available to users (multi-tasking mode)

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette3#1235]
While working on multi-tasking mode, and if I filter out the "hard" tasks, I would not expect the same tasks to be offered after completing the current task, since I already set in my task page to filter these out.

Below are a few screenshots in multi-tasking mode:

### Tasks marked as "Hard" are filtered out
![image](https://user-images.githubusercontent.com/5821688/82111651-3a1c6d80-9779-11ea-982a-ac53f4f99881.png)

### Nearby tasks on offer after completing a task still includes the "hard" tasks
![image](https://user-images.githubusercontent.com/5821688/82111679-6c2dcf80-9779-11ea-9f89-fcc5cf51a8ab.png)

**Comment by mvexel** [comment]
Thanks for reporting. You are right, this seems a bit inconsistent. We'll look into a solution.

**Comment by CollinBeczak** [comment]
Is this still something we would want to do now that the "working on multiple tasks widget" widget has been updated? It also wouldn't make much sense to do without directly adding filters to the nearby task map because then the user would need to exit the completion modal and enable "Too hard" tasks so they can see them in their nearby tasks completion modal view.

I think it would make more sense to go resolve this issue: https://github.com/maproulette/maproulette3/issues/2161, and then after that add filtering to the nearby tasks widget if that is something still desired after that fix. And I think that the filters persisting between the widget and the modal would be confusing for some users, but more feedback on that would be appreciated if it is desired.

**Comment by mvexel** [comment]
agree
