### ISSUE TITLE
Toggle proposed tag changes on and off.

### ISSUE THREAD

**Issue by atiannicelli** [maproulette/maproulette3#1494]
When working on tasks that have proposed changes the options for the user change to just "yes" and "no" to accept the suggestion, or label the issue as "not an issue". This makes it hard to fix an issue when the suggestion is wrong or not complete.

Use Case:
looking at a task, I see the issue that is being flagged, but the suggestion is not correct. So I want to be able to edit the map to fix the issue, and then return to the task and be able to click the "fixed it" button like I can for tasks that don't have suggestions.

Options:
1) Have a button to ignore/disable suggestion and then the task screen would go back to what it normally does.
2) Add the Edit button even if the suggestion is there. 

Here is an example of what the proposed changes look like. In this example I'd like to be able to edit the map to fix the location of the crossing as well as the tag.
https://maproulette.org/challenge/15923/task/75734873

**Comment by nrotstan** [comment]
Hi @atiannicelli , if you click "Show all Tags" at the top-right of the Proposed OSM Tag Changes and then click the edit (pencil) icon, you can modify the tags.

If it needs more than tag changes to fix, then it's really beyond the scope of a "tag fix" task.

**Comment by atiannicelli** [comment]
@nrotstan 
What I was trying to express is that I would like to provide two possible fixes for cases where a tag change fix may be correct or a geometry fix may be correct.
For example, if there exists a highway crossing a railway with an incorrect or empty value for level_crossing for the intersecting node, there are two possible fixes:
1) Add railway=level_crossing|crossing to the node (depends upon the crossing ways)
2) Delete the node (geometry change), which will(?) open up an editor to allow the user to split the way appropriately and add the correct layer tags (for example, where the TIGER import added bad intersections between highways and railways).

For (1), the current UI works well. If it is an either-or change, it no longer works as well.

Example workflow:
User looks at aerial and the tag change, hits No on the question Are the proposed OSM tag changes correct? at which point the second option comes into play, where the change is viewed via JOSM or iD.

**Comment by mvexel** [comment]
@atiannicelli I think the suggestion in itself is a valid one. The main reason for closing this (and @nrotstan feel free to jump in here) is that the quick fix task type is meant to have a simple, straightforward decision path. We're already 'compromizing' a bit with the "show all tags" function. But I would be hesitant to make changes to the flow, particularly because we haven't gained a whole lot of real world experience with the quick fix challenges yet. I will keep this suggestion as input on how to further develop the quick fix feature.

As a workaround for your current use case I would suggest using the fallout from the quick fix challenge to create a follow up challenge. You would instruct mappers to add a MR tag, something like `needs_edit` when they click 'No' (the suggested fix is not correct). When the challenge is done, or at any time you wish really, you would retrieve those tasks and use them to populate a conventional challenge with the appropriate instructions. You could even have multiple outcomes identified with separate MR Tags.

Please continue to discuss, we're definitely open to hearing feedback from the community about this relatively new aspect of MapRoulette. Thanks.

**Comment by atiannicelli** [comment]
Totally understood. Thanks for the reply and the suggestion.

One other request (that would also have solved this) coming from our mappers was a request to be able to toggle the "proposed changes" on and off. Kind of a slider or a setting in the users layout to "disable/enable proposed changes". That gives mappers that are a bit more experienced the ability to turn off the proposed changes if they want to be able to edit as usual.

**Comment by nrotstan** [comment]
I agree with @mvexel that we're still learning, and I openly acknowledge that our current Tag Fix workflow isn't suitable for all challenges, including those that could contain a mix of tag-fix and geometry-fix needs. For those types of challenges we do offer the full ["cooperative" workflow](https://learn.maproulette.org/documentation/creating-cooperative-challenges/#content) where the proposed changes are loaded into JOSM and can then be applied or edited however the mapper chooses, including making geometry changes. Those are JOSM-only currently, so would likely leave out novice mappers, but I'm guessing a tag-fix challenge that also sometimes expects geometry changes would likely be too much for novice users anyway.

Also, as an aside since we're on the topic, in the next release we're adding the "Edit Tags" control to the primary controls of the Tag Fix widget so that it will be more visible and won't require users to first click "Show all Tags" to discover it.

**Comment by atiannicelli** [comment]
Just a follow up on this topic... After talking with @mvexel and others I just wanted to post the updated request here that I think has merit, in hopes that we can get this topic reopened or a new one created to address the issue. What we discussed was that there are some workflows that are hampered by the fact that the edit button doesn't exist when proposed changes are presented to the mapper. 
1) One workflow that is interrupted is when a task is opened with a proposed change that looks good to the mapper, but a bit more info is needed to verify that the change is indeed correct the mapper may wan to open the editor to poke around and validate surrounding data or even street images of the feature. Once the issue has been validated the mapper may pop back into the MR task and choose "Yes" to indicate that the proposed change is correct. This workflow is difficult though because there is no edit button when the proposed changes are visible.
2) Another workflow happens when the proposed change may fix the immediate issue, but a small (non-tag related) change also should be included to make the feature completely correct. One such case is when a street crosses a railroad and there is no "railway=level_crossing" tag on the intersection node. The proposed change says to add a "railway=level_crossing" tag. That is correct, but a quick view of the issue also shows that a node nearby is currently tagged as a level crossing, but it is not at the intersection. The correct fix would be to add the "railway=level_crossing" tag to the intersection node AND edit the other node so that the level_crossing tag is removed... or just remove that other node. Both of those actions require opening an editor to make the secondary change to fix the situation. In this case a good mapper would want to be able to edit the map and then choose "I fixed It" in MR, but that is impossible when proposed changes are visible because the only two choices are to accept the tag change or reject it.

Both of these cases would be fixed by adding a toggle button to enable/disable proposed changes for this task. Disabling proposed changes would alter how the task is viewed by replacing the Yes and No buttons with the standard buttons available when proposed changes are not available for a task. Basically it would make a task look the same as if there were no proposed changes for this task.

For case 1 above the mapper could disable proposed changes and then click edit to open the editor. If the fix is validated as being simple as accepting the proposed change then the mapper could close the editor, "cancel editing", re"enable proposed changes", and then click "yes".
For case 2 above the mapper would disable proposed changes to edit the area, and when they see that it is more complicated than the single proposed change, then they could edit it in the editor, save it, then go back to MR and click "I fixed it!"

We have had feedback from many different mappers that they love the proposed changes, but just wish they still had the ability to open the editor.

**Comment by reichg** [comment]
This feature is highly desired by our team as well. The ability to open an editor with proposed tags will only make the auto-fix suggestions a more robust process. I think users will show more interest if they have the ability to make complimentary edits along with the fix-suggestion. Not only that but there are scenarios where it is essential to have the option to open an editor as stated above by Alex. The whole OSM workflow through MR will be more efficient.

**Comment by atiannicelli** [comment]
I had another mapper point out that only having the ability to answer yes or no doesn't give the mapper enough information to address the issue. Opening an editor allows the user to identify if the suggestion is appropriate. 
👍

**Comment by atiannicelli** [comment]
@mvexel Any interest in trying to make this change happen?
