### ISSUE TITLE
Challenge 'in limbo' after creating?

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#179]
I created challenge 2917 a couple hours ago. Returning to MapRoulette after that time:
* The challenge does not show up in search
* When I go to http://maproulette.org/mr3/browse/challenges/2917 it doesn't load. (It just shows the default page with the challenge list.)

**Comment by mvexel** [comment]
Update, search still won't turn up my challenge (type 'Utah' in search field)

**Comment by nrotstan** [comment]
This is because the parent project is not visible. The direct challenge URL (http://maproulette.org/mr3/challenge/2917 in this case) will work if the project is not visible, but "browsing" the challenge will not (and it won't show up in search results).

Surfacing an error message in this case would probably make sense. Related to #185, it's likely worth giving some thought as to how challenge links should behave for whom depending on the visibility of the challenge and parent. Right now it's admittedly confusing.

**Comment by mvexel** [comment]
Huh, how could I have missed that. Sorry for wasting everyone's time here :/
