### ISSUE TITLE
Archived projects still available

### ISSUE THREAD

**Issue by tastrax** [maproulette/maproulette3#1895]
https://github.com/microsoft/Open-Maps/issues/49

Archived projects look to be still available via a direct link. https://maproulette.org/browse/challenges/13837

Not sure that this should be allowed where data being used has incompatible licence.

**Comment by mvexel** [comment]
This is the expected behavior. The Challenge was automatically archived last year because the tasks had gotten stale (the Challenge was not refreshed in 6 months). Archiving does not mean that the Tasks are gone, but the Challenge is no longer discoverable.

If there is an issue with the Challenge and the Tasks should be permanently deleted, the Challenge owner should take this step and delete the Challenge entirely.

**Comment by mvexel** [comment]
Since this is expected behavior and the linked challenge is no longer on MapRoulette, I consider this issue closed.
