### ISSUE TITLE
Document geojson-format to create a challenge from

### ISSUE THREAD

**Issue by pietervdvn** [maproulette/maproulette3#1951]
**Is your feature request related to a problem? Please describe.**

I'm documenting how to setup a guided import with MapRoulette and MapComplete. For this, the source data to import should be converted into a geojson that can be understood by MapRoulette and which is uploaded during the 'Create a new challenge flow'.

It is clear that, when supplying points, every point will be shown as task.

However, it is not clear to me which properties are allowed in the geojson. @rlin did a great job figuring out some of the allowed properties (e.g. `tags` and `blurb`) but the precise semantixs are unclear.

Some questions I have, for example, are:

- I think that `tags` is a string of `;`-separated values. Is this correct? What if a tag should have ; as value?
- What other properties exist?
- What happens if I set a field in the form? E.g. if I upload a file where some entries have a `tags`-property and I fill out the `tags`-field in the form, will it ignore the properties in the file or rather work as fallback value if they are not set?
- what is a blurb exactly?

**Describe the solution you'd like**

Ideally, learn.maproulette.org would have a page listing the possible properties and their precise semantics.

I didn't find a relevant page, despite searching around for a bit.

**Comment by pietervdvn** [comment]
Also see #1737

**Comment by mvexel** [comment]
I agree this really needs attention... 

@ljdelight @jschwarz2030 do you know if it's possible to generate better [swagger documentation](https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json&docExpansion=none#/Task/create) with inline comments or should we go the route of adding a manually written page on learn.maproulette.org?

**Comment by jschwarz2030** [comment]
I believe a new page on learn.maproulette.org would be better, since swagger has been difficult to scale to our documentation needs, especially when providing details on nested data objects and data types and sufficient context for our users with a range of engineering skills.

Perhaps a good starting point would be a living document on hackmd.  @pietervdvn since you're already creating a document, I can assist you if you're open to starting/managing this endeavor.

to answer a few of your initial questions, 

- Tags are separated by commas and tags can contain semicolons
- other properties
```
checkinComment: "#maproulette"
dataOriginDate: ""
defaultBasemap: -1
defaultBasemapId: ""
defaultPriority: 0
defaultZoom: 18
description: "asdf"
difficulty: 2
enabled: true
featured: false
highPriorityRule: "{}"
instruction: "asdf"
limitReviewTags: false
limitTags: false
localGeoJSON: 
lowPriorityRule: "{}"
maxZoom: 19
mediumPriorityRule: "{}"
minZoom: 3
name: ""
overpassTargetType: null
parent: 4
presets: []
requiresLocal: false
tags: "foo,bar"
taskStyles: []
```

- What happens if I set a field in the form? E.g. if I upload a file where some entries have a tags-property and I fill out the tags-field in the form, will it ignore the properties in the file or rather work as fallback value if they are not set?
I searched for a bit on this in the code and i don't see tags getting set on tasks during challenge/task creation.  only when a task is mapped or reviewed.  I could be wrong though.    
    
- what is a blurb?  
It appears a blurb is just a secondary description field


You can contact me on OSM slack as well.

**Comment by jschwarz2030** [comment]
There's a testChallenge object here https://github.com/osmlab/maproulette-java-client/blob/dev/src/test/resources/challenges/testChallenge.json but it isn't exhaustive

**Comment by tsun812** [comment]
Here is the list of challenge properties with their semantics if you are interested: 
https://hackmd.io/@RGqHG6yhT3SGgsiGwQ0zPA/r18m6Z7Gh

Pls note that if may not work as expected if you try to add these properties via geojson, as they will get overridden by fields in create challenge form.

**Comment by matkoniecz** [comment]
Would it be possible to move it into some docs kept in repository? Not on some third party site where it may become deleted at any time?
