### ISSUE TITLE
Allow search for Challenges in Project Search

### ISSUE THREAD

**Issue by mgcuthbert** [maproulette/maproulette3#205]
In the Admin (or Create) area, you can search for projects but not challenges. So if you have a really long list of challenges, or manage multiple projects it is difficult to wade through everything to find what you are looking for. Especially if you have access to many projects. I would suggest allowing some search functionality for challenges as well as projects.

**Comment by mvexel** [comment]
agreed. It would be nice to allow searching by challenge id, if you know it. Use case is that folks email me from time to time with problems with a particular challenge and they give me the ID. Since the admin page URL for the challenge also contains the project name (which I then don't know) I'd need to ask them for the project name.

**Comment by mvexel** [comment]
Nice that this is implemented now. I was just now wanting that feature again :)
