### ISSUE TITLE
OFF TOPIC- Do we have a list of the most fundamental quests for a country?

### ISSUE THREAD

**Issue by chrisdebian** [maproulette/maproulette3#2073]
Hi, all.

I have written an [OSM diary](https://www.openstreetmap.org/user/chris_debian/diary) regarding the 'quality' of OSM data, in different countries. I'm wondering whether it's possible to have a 'league table' of the different standards of data in each country. In order to do this, I would need to know what is fundamentally important, in a country or entity, so countries can be ranked. For example, the road network? Number of hospitals? Something else?

In order to assess the data coverage in an area, I'd like to try to understand what Maproulette contributors consider to be important. Do we have a list of priorities?

Some interesting work has already been done [here](https://streetcompleteness.haukauntrie.de/), for statistics.

Please could you look at my diary entry, and either comment there, or here, or both :-)

Many thanks,

Chris
chris_debian

**Comment by mvexel** [comment]
We rely on local communities and individuals to bring challenges to mappers' attention. Since anyone can create challenges, it's not possible for MapRoulette to make sense of which ones are more important than others.

MapRoulette has some tools available internally, for example, you can zoom and pan the map to limit what you see in the challenge list, and rank those by popularity.

You could use the MapRoulette API in a creative way to create something that is closer to what you want.
