### ISSUE TITLE
[Rapid Integration bug] Unable to square building

### ISSUE THREAD

**Issue by atiannicelli** [maproulette/maproulette3#2085]
When I opened a specific building from maproulette and tried to square it it tells me that "it can't be made square because parts of it have not yet been downloaded". I tried the same building in native rapid and it works.

1. Go to [this link](https://maproulette.org/challenge/38974/task/178613924?#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1025859041&map=20.00/41.86001/-72.29921)
2. Right click on the building to get the menu to come up.
3. Observe that squareing (and other stuff) is not available.

Here is a picture of what I'm seeing
<img width="1792" alt="Screenshot 2023-08-23 at 12 49 13 PM" src="https://github.com/maproulette/maproulette3/assets/5851115/562afa30-7041-4736-a3dd-5dfddb1286dc">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version [v3.13.0](https://github.com/maproulette/maproulette3/releases/tag/v3.13.0)

**Comment by CollinBeczak** [comment]
It worked when i looked at it. it could be related to a specific workflow or was fixed by a recent release from us or the mapping editors plugins. Without looking into this thoroughly, im not sure if this is still an issue. If you can figure out the specific workflow this happens, (example: "find challenge page" -> "specific challenge dashboard" -> "task with task editor mode classic")  or multiple, that would be useful in fixing this issue quickly.
