### ISSUE TITLE
Don't offer "too hard" tasks again after they are marked 'too hard' 2 times

### ISSUE THREAD

**Issue by joostschouppe** [maproulette/maproulette3#217]
I don't think tasks marked "too hard" were offered again to regular users in MR2. I was offered this task in MR3:
maproulette.org/mr3/challenge/2789/task/3115011
When I skipped it, the task status was changed to "skipped".
For me, it would seem logical that "too hard" is a "final status", not something that can be changed again.

EDIT: you can avoid this behavior by clicking on "Next task". Doing that, combined with "Load tasks by>proximity", you can get into an endless loop, e.g. between these two:
http://maproulette.org/mr3/challenge/2789/task/3115382
http://maproulette.org/mr3/challenge/2789/task/3115271

**Comment by mvexel** [comment]
"Too hard" as a final status makes sense to me, Joost. 

I think I have observed this 'endless loop' behavior myself once or twice. I'll break that out as a separate issue if you don't mind.

**Comment by mvexel** [comment]
Thinking about this again with @nrotstan -- mappers can mark tasks as too hard for different reasons. It can be because it's too hard *for them* or because there's no imagery for example, in which case it would be too hard / impossible *for anyone* to solve it. 

We don't want to introduce yet another status / option, so here's what we think is an elegant solution:

* The title of the button remains the same
* When a task is marked as 'Too Hard' for the first time, the behavior stays the same as it is now
* When a task is marked as 'Too Hard' for a second time, the task is made invisible

That would probably mean that we need a new internal task status for that second case.

**Comment by nrotstan** [comment]
Not the same thing, but PR maproulette/maproulette2#607 gave server owners the ability to stop serving too-hard tasks to mappers.

**Comment by mvexel** [comment]
Revisiting -- keeping this one alive. I think it makes sense for Challenge creators to be able to set the number of times a task should be marked 'too hard' before it is not served again. The default should be 1, reflecting the current behavior, but it could be up to 5.

Ideally a user who marked a task as too hard would not get this task again regardless of number of times it's marked too hard overall.

**Comment by mvexel** [comment]
Tentatively adding this to the next point release but pending sizing

**Comment by mvexel** [comment]
[The documentation page](https://learn.maproulette.org/documentation/task-priority-rules/#content) about task priority rules points to this ticket and should be updated when we close this ticket.

**Comment by mvexel** [comment]
👍
