### ISSUE TITLE
Make it possible to remove a task by click on a marker on the map

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette3#2222]
![image](https://github.com/maproulette/maproulette3/assets/5821688/fc83ce6d-82ba-4013-9939-bdda75f30ce3)

**Is your feature request related to a problem? Please describe.**
While working on bundled tasks (like on the above photo, for example), a contributor is given a chance to remove any task from the bundle. However, it's not easy to determine which task is being referred to on the overview map .

**Describe the solution you'd like**
 A user can hover their mouse pointer, or click on a row representing the task,  and the corresponding marker on the map is highlighted, giving the user an idea which task is being referred to.

**Describe alternatives you've considered**
A contextual menu when a map marker is clicked, with an option to remove the task from the bundle.

**Comment by CollinBeczak** [comment]
Hey Govvin, thanks for making this ticket. There are some steps we need to complete before we can resolve this request. Ive got some goals for this widget, and i was curious if there were any other features that you think could be useful. These are the current goals for the widget:
1. Fix task locking, and bundling resets so no two users can work on the same task. When a user submits a bundle as skipped, all the tasks will be marked as skipped and the bundle will be broken back up into the individual tasks. If a user leaves their bundle with no completion status that it will be broken back up into individual tasks.(Complete)
2. Add bundling reset functionality. Make it so that if a user goes to a bundle, makes changes, doesnt submit the bundle and redirects, that the bundle will be reset to it previous status.
3. Add a button to reset the bundle for the user
4. Add the map to the bundled view(You can see an example of the end goal in the above pr).
5. Make it so that you can add and remove tasks from a bundle with the map.

If there are other situations that are not considered with these fixes, or other features that would be useful, please let me know as i get to work fixing the widget.

**Comment by govvin** [comment]
@CollinBeczak 

That looks like a very comprehensive feature for working with bundled tasks!
