### ISSUE TITLE
Next nearby task is the one I marked as "Can't complete"

### ISSUE THREAD

**Issue by vmartyanov** [maproulette/maproulette3#2292]
I found a task I can't complete and marked it as "can't complete" of course. From this moment I expect I'll never see it as a next task. Then weird behavior happened: I'm fixing other tasks with "next task will be nearby" option. And at one moment the next task is the one I marked as "can't complete" and definitely not the nearest.

I would not see tasks I can't complete because I already decided - I can't!

I made some googling and found this bug: https://github.com/maproulette/maproulette3/issues/1857 and seems it's my case: seems "can't complete" is ignored when looking at highest priority tasks. Could you please look at this?

**Comment by CollinBeczak** [comment]
These are related tickets to help understand the problem at hand and expected behavior. This issue will take higher priority, and we'll get a fix for this as soon as we can.

https://github.com/maproulette/maproulette3/issues/2292
https://github.com/maproulette/maproulette3/issues/217
https://github.com/maproulette/maproulette-backend/pull/607
https://github.com/maproulette/maproulette3/issues/1857
https://github.com/maproulette/maproulette3/issues/2018
