### ISSUE TITLE
OSM History widget in a layout automatically add openstreetmap.org/node/ extension

### ISSUE THREAD

**Issue by TomaszKozlowski-TomTom** [maproulette/maproulette3#2323]
**Describe the bug**
While using **OSM History** widget in MapRoulette layout, there is a defined www.openstreetmap.org/node/osmid path defined, so user is mislead with information about the feature to be edited.

**Expected behavior**
OSM History should correctly guide users to proper feature served in a MapRoulette.

**To Reproduce**
1. Go to Task
2. Click on 'View OSM' in **OSM History** widget
3. See node object showed instead of way which shows particular issue in MR related to way issue.

**Desktop (please complete the following information):**
Windows, Chrome

**Comment by salimbaidoun-tomtom** [comment]
Thank you for raising the issue @TomaszKozlowski-TomTom . when using this widget mappers can be mislead

**Comment by CollinBeczak** [comment]
I've looked into this, and to me, it appears that the "View OSM" links/buttons are working as expected.

Example of a working node link:
<img width="541" alt="Screenshot 2024-04-23 at 9 25 02 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/e85dcea3-e845-477d-87d7-6591c2c081d1">
<img width="485" alt="Screenshot 2024-04-23 at 9 25 17 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/f0e1d932-0ff7-4ca3-9f7a-c28328623cc0">

Example of a working way link:
<img width="535" alt="Screenshot 2024-04-23 at 9 25 35 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/ca37ab7c-3a96-4720-a108-23e521561ba7">
<img width="487" alt="Screenshot 2024-04-23 at 9 25 52 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/e9dab990-0022-43b1-a08f-c67176265a98">

I'm not a mapper, so there could be something I'm missing. If that's the case, please let me know.

It would also be useful if you could walk through examples within an example task or challenge where this issue is prevalent. The more detailed examples you can provide, the better.

**Comment by TomaszKozlowski-TomTom** [comment]
Hi Collin,
thank you for taking this up:
https://maproulette.org/browse/challenges/44791
This is a challenge when issue was observed first time, Norway. I'm not sure if there is something NOK in challenges prep step, loaded tasks and I have no clue why nodes from different countries are poping up here. Please have a look on couple of tasks:
[Task 224388999 2](https://maproulette.org/challenge/44791/task/224388999) – “View OSM” leads to a place in France.
[Task 224388641 1](https://maproulette.org/challenge/44791/task/224388641) – “View OSM” leads to a place in US.
[Task 224388624 1](https://maproulette.org/challenge/44791/task/224388624) – “View OSM” leads to a place in Italy.

We may have some in NLD as well:
https://maproulette.org/browse/challenges/44785

Can you confirm that indeed MR behaves as expected and if yes, how can I fix this issue at my end. If that is the bug, what is estimated plan to solve it, if any?

Thank you very much for prompt reaction and help, appreciated!

**Comment by CollinBeczak** [comment]
It seems like there is more than one issue in that first challenge. [Task 224388999](https://maproulette.org/challenge/44791/task/224388999) supposedly doesn't exist. I found this out when trying to bundle the task, and I received this message in the network tab: "Key (task_id)=(224388624) is not present in table 'tasks'." Additionally, it overlaps with [Task 225341218](https://maproulette.org/challenge/44791/task/225341218) and uses the same OSM ID. That is definitely a bug, but I don't think it's directly related to your issue.

There seems to be something wrong with the generation of the GeoJSON for your challenge. I'm not sure whether the issue lies on MapRoulette's side or not. Currently, in the output of the GeoJSON, there are a large number of points (nodes) and not a single linestring (way). This is why the history widget is pointing to a node with a matching feature ID, and why you see points instead of outlined buildings in MapRoulette.

Given the GeoJSON that is currently being used by the challenge, the widget and maps are working as expected. It's likely that there was an issue with the file you submitted here, or its setup:

<img width="941" alt="Screenshot 2024-04-23 at 12 04 38 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/5ae7db89-b65d-4aad-a601-406bd3065582">

Could you share the file used to create the challenge so I can verify whether or not it's a MapRoulette issue? If the file is too large for github, my email is ctbeczak08@gmail.com. Or if you are in the maproulette slack community you could also contact me there @CollinBeczak.

**Comment by TomaszKozlowski-TomTom** [comment]
Hi Collin,
I uploaded here a file which is an input for our challenge:

[NOR_Spiky_Buildings_Q1.zip](https://github.com/maproulette/maproulette3/files/15091723/NOR_Spiky_Buildings_Q1.zip)

Small explanation for that:
osmid is an id of building which is incorrect and has a spike,
point coordinates - this is a node which is a part of a building which is served in the challenge

Couple of tasks where feature in View OSM widget are referring to node object, while our osmid relates to building polygons:
Task: [225340808](https://maproulette.org/admin/project/48466/challenge/44791/task/225340808/inspect) - View OSM history sends us to Algeria
Task: [225340659](https://maproulette.org/admin/project/48466/challenge/44791/task/225340659/inspect) - View OSM history sends us to Romania
Task: [225340809](https://maproulette.org/admin/project/48466/challenge/44791/task/225340809/inspect) - View OSM history sends us to Austria
Task: [225340688](https://maproulette.org/admin/project/48466/challenge/44791/task/225340688/inspect) - View OSM history sends us to France

If you need more information from my side, just drop a comment.

Thank You!

**Comment by CollinBeczak** [comment]
So here is the issue, you are trying to link to the way Id with a point, and maproulette interprets that as a node. That first task points to a node [997877580](https://www.openstreetmap.org/node/997877580/history) in algeria with the osm id, and the building you are looking for is way [997877580](https://www.openstreetmap.org/way/997877580/history). Both that node and way have the same id but link to two different objects. 

Instead of using the way id as the osm id in your geojson, you need to select a node inside of the way. There is a dropdown in the way that hads all the nodes you can select from.
<img width="1189" alt="Screenshot 2024-04-24 at 1 27 32 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/3b55aada-55e0-47eb-936d-6bb0517851b6">

<img width="1207" alt="Screenshot 2024-04-24 at 1 28 47 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/3bea0f7b-28e6-416b-834c-26eb7918a8f5">

So instead of node/997877580 here, it would be node/9213751767
<img width="1155" alt="Screenshot 2024-04-24 at 1 29 01 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/9a7527f5-f808-4410-8f88-72f5202bacfb">

**Comment by TomaszKozlowski-TomTom** [comment]
Thank You for your analysis. Pointing node which is a part of the building is not so obvious, because that node can be a part of two or more different buildings. We will correct our input files to avoid confusions for the users.

Greetings!

**Comment by CollinBeczak** [comment]
No problem, I learned quite a bit from looking into this! If you run into anything else that doesn't seem right, or have a feature request, feel free to open another ticket and another developer or I will investigate it as soon as we can.
