### ISSUE TITLE
sort=tasks_remaining fails

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#2324]
**Please Read First**
* If you are having **issues creating your own Challenges**, please make sure you carefully read the MapRoulette [documentation](https://learn.maproulette.org/documentation/), specifically the section about Creating and Managing Challenges. If that doesn't help you, please post to the [OSM community forum](https://community.openstreetmap.org) with the hashtag **#maproulette**. 
* If you would like to report a Challenge you think is causing bad edits to OSM, please raise the issue with the Challenge owner first using the *Get In Touch* feature on the Challenge home page. If they fail to respond, please post to the [OSM community forum](https://community.openstreetmap.org) with the hashtag **#maproulette**.
* There is a [separate repository for the MapRoulette back end](https://github.com/maproulette/maproulette-backend/issues). If your report pertains to the API / back end, please submit it there.

Thanks for helping us make MapRoulette great for everyone!

**Describe the bug**

https://maproulette.org/browse/challenges?query=mismatch&sort=tasks_remaining does not work

https://maproulette.org/browse/challenges?query=mismatch works

**Expected behavior**

Going to https://maproulette.org/browse/challenges?query=mismatch and selecting sort order works

**To Reproduce**
1. Go to https://maproulette.org/browse/challenges?query=mismatch
2. Click on sort by
3. Select "tasks remaining"

**Screenshots**

![screen11](https://github.com/maproulette/maproulette3/assets/899988/2248b76d-d71a-4477-ba6f-a533c80f6604)
![screen12](https://github.com/maproulette/maproulette3/assets/899988/e06839d1-caf2-45c7-9972-f5b411de4ce4)

**Desktop (please complete the following information):**
 - OS: Lubuntu 20.04
 - Browser: Firefox
 - Version: 124.0.2
 
**Additional context**
I am forwarding report I got.

**Comment by ljdelight** [comment]
This is likely a UI bug. 

Visiting the link <https://maproulette.org/browse/challenges?query=mismatch> sends a request to the backend `/api/v2/challenges/extendedFind` ([req](https://maproulette.org/api/v2/challenges/extendedFind?cLocal=0&cStatus=3%2C4%2C0%2C-1&ce=true&cs=mismatch&limit=50&order=DESC&page=0&pe=true&sort=popularity))
with parms
```
cLocal=0
cStatus=3%2C4%2C0%2C-1
ce=true
cs=mismatch
limit=50
order=DESC
page=0
pe=true
sort=popularity
```

then in the UI I navigate to the `Sort By` field and select 'Tasks Remaining' and it fires off another request to `/api/v2/challenges/extendedFind` ([req](https://maproulette.org/api/v2/challenges/extendedFind?cLocal=0&cStatus=3%2C4%2C0%2C-1&ce=true&cs=mismatch&limit=50&order=ASC&page=0&pe=true&sort=tasks_remaining))
with parms 
```
cLocal=0
cStatus=3%2C4%2C0%2C-1
ce=true
cs=mismatch
limit=50
order=ASC
page=0
pe=true
sort=tasks_remaining
```

The difference between request query parameters are the `order` and `sort`. Both responses send http `200`, are around 5kB gzip'd, send exactly 13 results, and took around 200ms. 

Since the API calls are successful some other item is responsible for the UI displaying "Cannot find matching name"
