### ISSUE TITLE
Multi Edit not working.

### ISSUE THREAD

**Issue by wzbartczak** [maproulette/maproulette3#2335]
Multiple tasks cannot be edited at the same time, once multiple tasks are selected, they cannot be edited together. Only one task is redirected to JOSM. There is no button to connect the tasks.

**Comment by CollinBeczak** [comment]
What challenge are you having this issue with? I've been looking into this, and the common problems i see when josm isnt working is due to the geojson thats passed.

This is the multi task working with ways:
<img width="1110" alt="Screenshot 2024-05-14 at 12 27 40 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/ef3228ef-6ba7-49c1-81a6-1d7a08812e55">
This is the multi task working with nodes:
<img width="1046" alt="Screenshot 2024-05-14 at 12 31 39 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/d6376e85-6f26-4bcc-bf47-d56e2c715474">

**Comment by wzbartczak** [comment]
I had a problem with the tasks from the link:
https://maproulette.org/challenge/43752/task/217352503

Today it worked fine, yesterday the “Start Bundling Task” button did not show up.

![image](https://github.com/maproulette/maproulette3/assets/30273671/fb1855be-73e0-4350-bcaa-e69d504fa9f5)

Refreshing the page did not help. Did you change anything in between?

**Comment by CollinBeczak** [comment]
We had a deployment yesterday that may have fixed that issue. If you encounter this issue again, run into any more unexpected behavior, or have any enhancement ideas, please let me know.
