### ISSUE TITLE
While task revision from filtered project, next task opened is not from filtered project

### ISSUE THREAD

**Issue by TomaszKozlowski-TomTom** [maproulette/maproulette3#2468]
While doing task's revision editor, after revision completion click 'next' to get another task from the bucket, which is defined by him (as tasks to be reviewed from one project). When next task is opened, it is not from defined/filtered project bucket, as user wanted. With that, user has to jump to the filter again, find another task and continue revision. Task by task, this action has to be repeated.

**Comment by TomaszKozlowski-TomTom** [comment]
Any news about this bug? @CollinBeczak

**Comment by CollinBeczak** [comment]
Hmm... Im not 100% following the issue here, there is one workflow that i know of that fits your issue descriptions.

There are 5 different main workflows:
Completion
Revision (You could be talking about this one, but i dont see any filters related to this workflow)
Review (This one loosely matches your description, to me at least)
Inspect
ReadOnly

More info on the review workflow filters:

<img width="1437" alt="Screenshot 2024-10-29 at 11 26 09 AM" src="https://github.com/user-attachments/assets/06d6dbf4-e817-4df8-b8fa-4c44047ae021">

Above shows the filters that are used to filter the next available tasks, if the review workflow is what you are referring to than your issue would be fixed by simply adding a project filter, similar to the challenge filter as displayed above.

Let me know if i am miss interpreting something or you have more information. Images of the completion widget would also be useful to identify the specific workflow you are referring to.

**Comment by TomaszKozlowski-TomTom** [comment]
Hi Collin, as images and explanation below:

* user filters tasks from respective challenge:
![image (12)](https://github.com/user-attachments/assets/40a93e93-6520-4731-8c4c-081b0cf45773)

* after the revision user mark option review next filtered task
![image (13)](https://github.com/user-attachments/assets/608cb66a-e2e1-41ee-b643-2f5f485fe19d)

* next task is not from filtered challenge
![image (14)](https://github.com/user-attachments/assets/3b6fc069-811b-432c-8dbe-bac4b49d2d41)

**Comment by CollinBeczak** [comment]
Ok, thanks for clarifying that for me. In the optimal scenario we would maintain all the filters applied in the table list. 

Right now we only have these 5 filters, indicated in the adjust filters modal:

<img width="476" alt="Screenshot 2024-10-30 at 9 49 28 AM" src="https://github.com/user-attachments/assets/309178f9-dfe2-41d0-bdbe-49a78e1ae905">

<img width="514" alt="Screenshot 2024-10-30 at 9 40 28 AM" src="https://github.com/user-attachments/assets/2603bbf2-262f-464d-84b4-b056aa59d7b0">

To resolve your specific issue quickly, i can just add the project filter to that list. Ill get this included in our next deployment, which at latest should be Nov 11th, hopefully i can get it deployed sooner.

**Comment by TomaszKozlowski-TomTom** [comment]
May be hard as there is no specific project which is checked, we have different ones at one time even.
In this case, we are waiting for the feedback and possible solutions.

Thanks!

**Comment by CollinBeczak** [comment]
Have you experimented with using this button at all? 
![Image](https://github.com/user-attachments/assets/77b8b6e1-9998-4869-b479-1e68696e7519)

From what i can tell it does what you are looking for. If you apply any filters in the table, it persists those filters if you click that button. There may however be a bug with the button... I applied filters for 2 projects which narrowed down the list to 4 results, but i ended up only being able to work on 3 of them before being sent back to the review table.

**Comment by TomaszKozlowski-TomTom** [comment]
Thank You @CollinBeczak , this option works for us.
