### ISSUE TITLE
User saving task behavior

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#81]
When saving a task, once “Save” is clicked and it changes to “Unsave” it is unclear that in order to continue to the next task, the user needs to select one of the other 3 options - either “Skip,” “Fix,” or “Not an issue”

**Comment by mvexel** [comment]
This is by design -- not saying the design choice is necessarily right 😄 . The idea is that a user could look at the task, decide that it's somehow interesting to them by saving it, and then continuing to perform a next action on it.

Does that make sense, and how could we make that clearer if it does?

**Comment by nrotstan** [comment]
I made a few changes to try to reduce confusion.
* I separated the save task control from the rest of the task completion controls
* I changed it from a button to a switch
* I relabeled it to be "Track Task" instead of "Save Task" to avoid potential confusion with the idea of saving one's changes
* Likewise, on the User Profile page I changed the "Saved Tasks" header to "Tracked Tasks"
<img width="361" alt="track_task" src="https://user-images.githubusercontent.com/445970/36081096-59ddd29e-0f4f-11e8-8b19-2af08becc73e.png">

**Comment by samuelestabrook** [comment]
Very cool! Thank you for helping make sense of the logic here, I really like this feature.

**Comment by joostschouppe** [comment]
I find it very hard to understand exactly what the "Track task" thing does. Maybe a hint text on mouseover might help. Though if I understand it correctly, it seems like "something fun that few users need", and thus should not be in such a prominent place; maybe entirely at the bottom?
